# Generated by Django 4.0 on 2022-02-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('first', models.CharField(blank=True, max_length=200)),
                ('middle', models.CharField(blank=True, max_length=200)),
                ('last', models.CharField(blank=True, max_length=200)),
                ('header', models.CharField(blank=True, max_length=300)),
                ('birthday', models.DateField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('phone2', models.CharField(blank=True, max_length=12)),
                ('insta', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('prayers', models.TextField(blank=True, max_length=2000)),
            ],
        ),
    ]
